---

- name : Install docker in machine 
  shell : "yum install -y docker"

- name : docker compose part
  shell : "sudo curl -L https://github.com/docker/compose/releases/download/1.21.0/docker-compose-`uname -s`-`uname -m` | sudo tee /usr/bin/docker-compose > /dev/null"

- name : service file set up for compose
  shell : "sudo chmod +x /usr/bin/docker-compose"

- name : ensure docker is running
  shell : "sudo service docker restart"

- name: Populate docker-compose-master file
  template : src=docker-compose-master.j2 dest=/home/ec2-user/docker-compose.yml
#  when : ENV_NAME == "Jenkins_Master"

- name: populate config file for jenkins admin user
  template : src=config.xml.j2 dest=/home/ec2-user/config.xml

- name: populate jenkins job builder ini file
  template: src=jenkins_jobs.ini.j2 dest=/home/ec2-user/jenkins_jobs.ini

- name: populate sample jenkins job for jenkins job buider
  template: src=myfirstjob.yml.j2 dest=/home/ec2-user/myfirstjob.yml

- name: populate slave fucntions
  file: path=/home/ec2-user/slave-node state=directory

- name: populate config file for jenkins slave node
  template : src=config-slave.xml.j2 dest=/home/ec2-user/slave-node/config.xml

- name: populate config file for setup script
  template : src=setup.sh.j2 dest=/home/ec2-user/setup.sh

- name : run docker compose for master
  shell : "docker-compose up -d" 
